dist: trusty
sudo: false
language: cpp
compiler: gcc

os: linux

services:
  - docker

before_install:
  - docker pull danoan/dipacus:env
  - docker build . -t dipacus:build
  - docker run dipacus:build /bin/sh -c scripts/test-dipacus.sh
